Repository De-cal/6-Favorite_Photo-BE, pull requests merged in 2025-05, with the labels that each got.

#2 Feat/marketplace-sell
  .gitignore
  src/controllers/article.controller.js
  src/controllers/card.controller.js
  src/db/generated/prisma/edge.js
  src/db/generated/prisma/index-browser.js
  src/db/generated/prisma/index.d.ts
  src/db/generated/prisma/index.js
  src/db/generated/prisma/package.json
  src/db/generated/prisma/runtime/edge-esm.js
  src/db/generated/prisma/runtime/edge.js
  src/db/generated/prisma/runtime/library.d.ts
  src/db/generated/prisma/runtime/library.js
  src/db/generated/prisma/runtime/react-native.js
  src/db/generated/prisma/runtime/wasm.js
  src/db/generated/prisma/wasm.js
  src/db/prisma/prisma.js
  src/repositories/.gitkeep
  src/repositories/article.repository.js
  src/repositories/card.repository.js
  src/routes/index.js
  src/services/.gitkeep
  src/services/article.service.js
  src/services/card.service.js
Labels: BE, API

#4 feat/noti and point
  src/controllers/.gitkeep
  src/controllers/notificationController.js
  src/controllers/pointController.js
  src/repositories/notificationRepository.js
  src/repositories/pointRepository.js
  src/routes/index.js
  src/routes/notificationRouter.js
  src/routes/pointRouter.js
  src/services/notificationService.js
  src/services/pointService.js
Labels: Feature, BE, API

#5 Feat/marketplace sell
  src/controllers/article.controller.js
  src/controllers/card.controller.js
  src/controllers/notificationController.js
  src/controllers/pointController.js
  src/repositories/article.repository.js
  src/repositories/card.repository.js
  src/repositories/notificationRepository.js
  src/repositories/pointRepository.js
  src/routes/index.js
  src/routes/notificationRouter.js
  src/routes/pointRouter.js
  src/services/article.service.js
  src/services/notificationService.js
  src/services/pointService.js
Labels: BE, API

#6 Feat/마이갤러리 및 나의판매 페이지 백엔드 api제작
  src/controllers/article.controller.js
  src/controllers/card.controller.js
  src/db/prisma/mocks/photoCardMocks.js
  src/db/prisma/seed.js
  src/repositories/article.repository.js
  src/repositories/card.repository.js
  src/services/article.service.js
  src/services/card.service.js
Labels: Feature, BE

#7 feat: getAllArticles 구현
  src/controllers/article.controller.js
  src/repositories/article.repository.js
  src/routes/notification.router.js
  src/routes/point.router.js
  src/services/article.service.js
Labels: BE

#8 feat: 마켓플레이스 백엔드 api 연동
  src/controllers/article.controller.js
  src/repositories/article.repository.js
  src/services/article.service.js
Labels: Fix, BE, API

#10 fix:API호출부 수정-아티클컨트롤러
  src/controllers/article.controller.js
Labels: Fix, BE

#12 Chore: 필요없는 api호출 삭제
  src/controllers/article.controller.js
  src/repositories/article.repository.js
  src/services/article.service.js
Labels: Chore

#14 Feat/db 스키마수정&시드데이터추가
  src/db/prisma/migrations/20250527021155_/migration.sql
  src/db/prisma/schema.prisma
Labels: Fix, BE

#17 Feat/noti 알림기능 에러처리 코드 추가.
  src/repositories/notification.repository.js
  src/services/notification.service.js
Labels: Feature, BE

#18 Feat/img upload+포토카드 생성
  package-lock.json
  sample.jpg
  src/controllers/card.controller.js
  src/middlewares/upload.js
  src/routes/card.route.js
  src/routes/upload.js
  src/services/card.service.js
  src/uploads/1748336647000-sample.jpg
  src/uploads/1748337636100-sample.jpg
Labels: BE

#20 feat: 마켓플레이스 구매 & 교환 엔드포인트 완성
  src/controllers/article.controller.js
  src/repositories/article.repository.js
  src/routes/article.route.js
  src/services/article.service.js
Labels: Feature, BE, Endpoint

#22 Fix/create card
  src/controllers/card.controller.js
  src/repositories/card.repository.js
  src/uploads/1748407548746-sample.jpg
  src/uploads/1748407699251-sample.jpg
  src/uploads/1748407882285-sample.jpg
  src/uploads/1748411543615-sample.jpg
  src/uploads/1748411630331-sample.jpg
Labels: Fix, BE

#23 feat: 쿠키패치 함수 활용 FE api 연동.
  src/controllers/notification.controller.js
  src/controllers/point.controller.js
  src/repositories/point.repository.js
  src/routes/index.js
  src/routes/point.route.js
  src/services/point.service.js
Labels: BE, Refactor

#24 Feat/마이갤러리 api
  src/controllers/article.controller.js
  src/db/prisma/schema.prisma
  src/repositories/article.repository.js
  src/repositories/card.repository.js
Labels: Fix, BE

#26 Feat/marketplace infinite scrolling
  src/controllers/article.controller.js
  src/repositories/article.repository.js
  src/services/article.service.js
Labels: Chore, BE

#25 fix:마이갤러리 API 약간 수정
  src/repositories/card.repository.js
Labels: Fix, BE, Refactor

#27 Feat/마이갤러리api수정
  src/db/prisma/migrations/20250529052102_/migration.sql
  src/db/prisma/migrations/20250529085823_/migration.sql
  src/db/prisma/schema.prisma
  src/repositories/article.repository.js
  src/repositories/card.repository.js
Labels: Fix, BE

#28 Feat/marketplace sell
  src/controllers/article.controller.js
  src/controllers/card.controller.js
  src/repositories/article.repository.js
  src/repositories/card.repository.js
  src/routes/article.route.js
  src/services/article.service.js
  src/services/card.service.js
Labels: Feature, BE, Endpoint

#30 Feat/auth logout
  src/controllers/auth.controller.js
  src/routes/auth.route.js
  src/services/auth.service.js
  src/utils/auth.utils.js
Labels: Feature, BE, Refactor

#31 Feat/marketplace fix
  src/repositories/article.repository.js
Labels: Fix, BE

#33 Feat/noti 테스트용 알림 생성 함수 추가 및 알림 받아오기 함수, 읽음처리 함수 수정.
  src/controllers/notification.controller.js
  src/repositories/notification.repository.js
  src/routes/index.js
  src/routes/notification.route.js
  src/services/notification.service.js
Labels: Fix, Feature, BE

#37 feat: 마켓플레이스 구매자 엔드포인트
  src/controllers/article.controller.js
  src/repositories/article.repository.js
  src/routes/article.route.js
  src/services/article.service.js
Labels: Feature, BE, Endpoint

#38 fix:마켓플레이스 카드보유자 생성자로 수정
  src/repositories/article.repository.js
Labels: Fix, BE

#39 Feat/mk place detail seller
  src/controllers/article.controller.js
  src/repositories/article.repository.js
  src/repositories/card.repository.js
  src/routes/article.route.js
  src/services/article.service.js
Labels: Feature, BE

#40 Feat/auth
  src/controllers/auth.controller.js
  src/middlewares/auth.middleware.js
  src/services/auth.service.js
  src/utils/auth.utils.js
Labels: Fix, BE, Refactor

#41 Feat/marketplace sell
  src/controllers/article.controller.js
  src/repositories/article.repository.js
  src/services/article.service.js
Labels: Fix, Endpoint

#43 feat: 마켓플레이스 구매자 엔드포인트 작은 수정
  src/controllers/article.controller.js
  src/repositories/article.repository.js
  src/routes/article.route.js
  src/services/article.service.js
Labels: Feature, BE, Endpoint

#44 fix:나의판매페이지 API 수정
  src/repositories/article.repository.js
Labels: Fix, BE

#45 fix: 구매자 상세 불러오기 발행자 가져오도록 수정
  src/repositories/article.repository.js
Labels: BE, Endpoint, Refactor
