Repository De-cal/6-Favorite_Photo-BE, pull requests merged in 2025-06, with the labels that each got.

#46 fix:유저테이블 구글ID 추가
  src/db/prisma/migrations/20250601043125_google_o_auth/migration.sql
  src/db/prisma/schema.prisma
Labels: Fix, BE

#48 Feat/auth o auth
  .env.example
  package-lock.json
  package.json
  src/app.js
  src/config/passport.js
  src/controllers/auth.controller.js
  src/repositories/auth.repository.js
  src/routes/auth.route.js
  src/services/auth.service.js
  src/uploads/1748336647000-sample.jpg
  src/uploads/1748337636100-sample.jpg
  src/uploads/1748407548746-sample.jpg
  src/uploads/1748407699251-sample.jpg
  src/uploads/1748407882285-sample.jpg
  src/uploads/1748411543615-sample.jpg
  src/uploads/1748411630331-sample.jpg
  src/uploads/1748479884836-sample.jpg
  src/uploads/1748480767041-cloth1.jpg
  src/uploads/1748493408868-cloth1.jpg
  src/utils/auth.utils.js
Labels: Feature, BE, Refactor

#47 Feat/marketplace exchange
  .env.example
  .gitignore
  src/controllers/article.controller.js
  src/repositories/article.repository.js
  src/services/article.service.js
Labels: BE, Endpoint

#49 Feat/auth o auth
  src/utils/auth.utils.js
Labels: Chore

#51 feat: 구매자 교환 목록 불러오기 엔드포인트 구구현
  src/controllers/article.controller.js
  src/repositories/article.repository.js
  src/services/article.service.js
Labels: Feature, BE, Endpoint

#53 feat: 구글 회원가입 로그인 백엔드 기능 완성
  src/config/passport.js
  src/controllers/auth.controller.js
  src/repositories/auth.repository.js
Labels: BE, Refactor

#56 feat: 로그인과 회원가입 관련 struct 유효성 검사 추가
  src/structs/auth/loginRequest.struct.js
  src/structs/auth/signupRequest.struct.js
Labels: BE, Refactor

#55 feat: 구매 엔드포인트 품절 시 로직 보완
  src/repositories/article.repository.js
  src/repositories/card.repository.js
  src/services/article.service.js
Labels: Feature, BE, Endpoint

#58 Fix/month count change
  src/db/prisma/mocks/userMocks.js
  src/db/prisma/seed.js
  src/repositories/auth.repository.js
Labels: Fix, BE

#59 chore: 주석 이름 수정
  src/controllers/article.controller.js
  src/repositories/article.repository.js
  src/routes/article.route.js
  src/services/article.service.js
Labels: Chore

#61 Feat/marketplace sell
  src/controllers/article.controller.js
  src/repositories/article.repository.js
  src/repositories/card.repository.js
  src/routes/article.route.js
  src/services/article.service.js
Labels: Fix, Feature, BE

#64 ignore> upload/ 수정
  .gitignore
Labels: Fix

#70 Feat/seed Fix
  src/db/prisma/mocks/photoCardMocks.js
  src/db/prisma/mocks/userMocks.js
Labels: Feature, BE

#74 fix:const export default로 통일
  src/controllers/article.controller.js
  src/controllers/card.controller.js
  src/db/prisma/mocks/photoCardMocks.js
  src/repositories/article.repository.js
  src/repositories/card.repository.js
  src/repositories/notification.repository.js
  src/services/article.service.js
  src/services/card.service.js
  src/uploads/1749022226365-ë©íëª½.jpg
  src/uploads/1749029505353-ë©íëª½.jpg
Labels: Fix

#75 fix:교환 수정
  src/services/article.service.js
Labels: Fix

#76 Feat/create month
  src/controllers/card.controller.js
  src/routes/card.route.js
  src/services/card.service.js
Labels: Feature, BE
